spring:
  config:
    import: classpath:secrets.yml
  datasource:
#    url: ${mySQL.url}
#    username: ${mySQL.username}
#    password: ${mySQL.password}

#    docker settings for MySQL:
    url: ${dockerMySQL.url}
    username: ${dockerMySQL.username}
    password: ${dockerMySQL.password}

    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.user}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
        transaction:
          interceptor: TRACE
auth:
  issuers:
    google: https://accounts.google.com
    microsoft: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0